### ISSUE TITLE
Rename module

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_westvault_extras#1]
As discussed, this tool would be useful alongside https://github.com/bondjimbond/islandora_westvault - but the fact that both tools have the same name needs to be resolved. 

@mjordan suggested "islandora_westvault_extras"

Perhaps making it a bit more universal would be good, since non-Westvault users might also find it valuable... like "islandora_bag_info"?

**Comment by mjordan** [comment]
I prefer "islandora_westvault_extras" since it's specific to WestVault, not to bag-info.txt. I'll rename it.
